/**
 * types/index.ts
 * --------------
 * Centralized TypeScript interfaces for the LibLog system.
 * Institution: Calauan Community College (CCC)
 *
 * Strict No-Implicit-Any policy (per directive mvp_crud_tables.md).
 * All Supabase query results must be cast to these interfaces.
 *
 * SELF-ANNEALING NOTE — Supabase relational joins:
 *   `supabase.from('library_logs').select('*, patrons(full_name, patron_type)')`
 *   returns `patrons` as a SINGLE nested object (not an array), because
 *   patron_id is a many-to-one FK. Type it as `Patron | null`, NOT `Patron[]`.
 *   Typing it as an array would require `asserting` every access — avoid.
 */

// ─── Program ──────────────────────────────────────────────────────────────────
/** Academic program (BSPA, Midwifery, etc.) — referenced by patrons.program_id */
export interface Program {
  id: number;
  name: string;
  acronym: string;
}

// ─── Patron ───────────────────────────────────────────────────────────────────
/** Covers student, faculty, and visitor. `programs` is a joined relation. */
export interface Patron {
  id: string;
  full_name: string;
  unified_id: string;
  patron_type: 'student' | 'faculty' | 'visitor';
  program_id: number | null;
  year_level: number | null;
  created_at: string;
  /** Populated by: .select('*, programs(name, acronym)') */
  programs: Pick<Program, 'name' | 'acronym'> | null;
}

/** Payload for creating a new patron — id is generated by auth trigger */
export type NewPatron = Pick<Patron, 'full_name' | 'unified_id' | 'patron_type' | 'program_id' | 'year_level'>;

// ─── Book ─────────────────────────────────────────────────────────────────────
export interface Book {
  id: string;
  title: string;
  isbn: string;
  author: string;
  category: string;
  total_copies: number;
  available_copies: number;
  /** 'active' = available for borrowing; 'donated' = removed from circulation */
  status: 'active' | 'donated';
  created_at: string;
}

/** Payload for creating a new book — `id` and `created_at` generated by Supabase */
export type NewBook = Omit<Book, 'id' | 'created_at'>;

// ─── BookLoan ─────────────────────────────────────────────────────────────────
/**
 * Represents a row from `book_loans`. Schema (confirmed from live DB):
 *   status check: 'active' | 'returned' | 'overdue'
 *   due_date defaults to borrowed_at + 3 days (enforced at DB level).
 *   penalty_paid: tracks whether the ₱5/day overdue fine has been settled.
 */
export interface BookLoan {
  id: string;
  book_id: string;
  patron_id: string;
  borrowed_at: string;           // ISO 8601 timestamptz
  due_date: string;              // ISO 8601 timestamptz (borrowed_at + 3 days)
  returned_at: string | null;    // null = loan still active
  status: 'active' | 'returned' | 'overdue';
  penalty_paid: boolean;
}

/**
 * BookLoan with joined `books` and `patrons` relations.
 * Used by CirculationManager (active loans table) and OverdueDashboard.
 */
export interface BookLoanWithRelations extends BookLoan {
  books:   Pick<Book,   'title' | 'author' | 'isbn' | 'available_copies'> | null;
  patrons: Pick<Patron, 'full_name' | 'unified_id' | 'patron_type'>        | null;
}

/** Minimal payload to create a new loan — all other fields have DB defaults */
export type NewBookLoan = Pick<BookLoan, 'book_id' | 'patron_id'>;

// ─── LogEntry ─────────────────────────────────────────────────────────────────
/**
 * Represents a row from `library_logs` with the `patrons` relation expanded.
 *
 * SELF-ANNEALING FIX (Phase 3):
 *   The actual FK column is `student_id` (not `patron_id`). Corrected to match
 *   the live Supabase schema. Status also includes 'auto-closed' (from the
 *   `close_stale_library_sessions` scheduled function).
 *
 * `patrons` typed as `Patron | null` (single object) because student_id is a
 * many-to-one FK. Using Patron[] here would cause runtime access errors.
 */
export interface LogEntry {
  id: string;
  student_id: string;           // FK → patrons.id  (column is named student_id in DB)
  time_in: string;              // ISO 8601 timestamptz
  time_out: string | null;      // null = session still active
  status: 'active' | 'completed' | 'auto-closed';
  device_id: string | null;     // QR scanner device identifier
  /** Populated by relational select: patrons(full_name, patron_type, unified_id) */
  patrons: Pick<Patron, 'full_name' | 'patron_type' | 'unified_id'> | null;
}

/**
 * Extended LogEntry used by ReportGenerator.
 * The select includes `patrons.program_id` and the nested `programs(name, acronym)` join,
 * which requires a richer patron shape than the base LogEntry.
 * Using this type eliminates all `as any` casts in ReportGenerator.
 */
export interface LogEntryWithProgram extends Omit<LogEntry, 'patrons'> {
  patrons: (Pick<Patron, 'full_name' | 'patron_type' | 'unified_id'> & {
    program_id: number | null;
    programs: Pick<Program, 'name' | 'acronym'> | null;
  }) | null;
}


// ─── Auth (Zustand Store) ──────────────────────────────────────────────────────
import type { Session, User } from '@supabase/supabase-js';
// Re-export for consumers that need these Supabase types via our types barrel
export type { Session, User };

/**
 * Shape of the global auth state slice in Zustand.
 * `session` is null when logged out, populated after signInWithPassword.
 * `isInitialized` guards against the flash-of-login-screen on first load:
 *   it stays false until onAuthStateChange fires its first event, which is
 *   the correct moment to trust whether the user is logged in or not.
 */
export interface AuthState {
  session: Session | null;
  isInitialized: boolean;
}

/** Actions attached to the auth slice */
export interface AuthActions {
  setSession: (session: Session | null) => void;
  setInitialized: () => void;
  signOut: () => Promise<void>;
}

export type AuthStore = AuthState & AuthActions;

