/**
 * types/index.ts
 * --------------
 * Centralized TypeScript interfaces for the LibLog system.
 * Institution: Calauan Community College (CCC)
 *
 * Strict No-Implicit-Any policy (per directive mvp_crud_tables.md).
 * All Supabase query results must be cast to these interfaces.
 *
 * SELF-ANNEALING NOTE — Supabase relational joins:
 *   `supabase.from('library_logs').select('*, patrons(full_name, patron_type)')`
 *   returns `patrons` as a SINGLE nested object (not an array), because
 *   patron_id is a many-to-one FK. Type it as `Patron | null`, NOT `Patron[]`.
 *   Typing it as an array would require `asserting` every access — avoid.
 */

// ─── Patron ───────────────────────────────────────────────────────────────────
/** Replaces the old 'students' table. Covers student, faculty, and visitor. */
export interface Patron {
  id: string;
  full_name: string;
  id_number: string;
  /** Discriminated union — matches the `patron_type` CHECK constraint in Supabase */
  patron_type: 'student' | 'faculty' | 'visitor';
}

// ─── Book ─────────────────────────────────────────────────────────────────────
export interface Book {
  id: string;
  title: string;
  isbn: string;
  author: string;
  category: string;
  total_copies: number;
  available_copies: number;
}

/** Payload for creating a new book — `id` is generated by Supabase */
export type NewBook = Omit<Book, 'id'>;

// ─── LogEntry ─────────────────────────────────────────────────────────────────
/**
 * Represents a row from `library_logs` with the `patrons` relation expanded.
 *
 * IMPORTANT: `patrons` is typed as `Patron | null` (single object) because
 * patron_id is a many-to-one foreign key. The Supabase JS client returns the
 * joined relation as an object when the FK points to a single row.
 * Using `Patron[]` here would be incorrect and would cause runtime errors
 * when accessing patrons.full_name.
 */
export interface LogEntry {
  id: string;
  patron_id: string;
  time_in: string;           // ISO 8601 timestamp string
  time_out: string | null;   // null = still checked in
  status: 'active' | 'completed';
  /** Populated by the relational select: patrons(full_name, patron_type) */
  patrons: Pick<Patron, 'full_name' | 'patron_type'> | null;
}

// ─── Auth (Zustand Store) ──────────────────────────────────────────────────────
import type { Session, User } from '@supabase/supabase-js';
// Re-export for consumers that need these Supabase types via our types barrel
export type { Session, User };

/**
 * Shape of the global auth state slice in Zustand.
 * `session` is null when logged out, populated after signInWithPassword.
 * `isInitialized` guards against the flash-of-login-screen on first load:
 *   it stays false until onAuthStateChange fires its first event, which is
 *   the correct moment to trust whether the user is logged in or not.
 */
export interface AuthState {
  session: Session | null;
  isInitialized: boolean;
}

/** Actions attached to the auth slice */
export interface AuthActions {
  setSession: (session: Session | null) => void;
  setInitialized: () => void;
  signOut: () => Promise<void>;
}

export type AuthStore = AuthState & AuthActions;

